name: Test Proxy Servers

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test-proxies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: |
          npm install

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq bc

      - name: Download and install Sing-box
        run: |
          SINGBOX_VERSION="1.11.15"
          echo "Installing Sing-box version: $SINGBOX_VERSION"
          wget https://github.com/SagerNet/sing-box/releases/download/v${SINGBOX_VERSION}/sing-box-${SINGBOX_VERSION}-linux-amd64.tar.gz
          tar -xzf sing-box-${SINGBOX_VERSION}-linux-amd64.tar.gz
          RELEASE_DIR_NAME="sing-box-${SINGBOX_VERSION}-linux-amd64"
          if [ -f ./${RELEASE_DIR_NAME}/sing-box ]; then
            sudo mv ./${RELEASE_DIR_NAME}/sing-box /usr/local/bin/sing-box
          elif [ -f ./sing-box ]; then
            sudo mv ./sing-box /usr/local/bin/sing-box
          else
            echo "Sing-box binary not found!"
            exit 1
          fi
          sudo chmod +x /usr/local/bin/sing-box
          sing-box version

      - name: Run proxy tests
        env:
          LINKS_HIGH: ${{ secrets.LINKS_HIGH }}
        run: |
          node index.js

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions-bot@users.noreply.github.com'

      - name: Remove old files and add new ones
        run: |
          # Удаляем старые версии файлов из истории
          if [ -f db.json ]; then
            git rm --cached db.json 2>/dev/null || true
          fi
          
          if [ -d checked ]; then
            git rm -r --cached checked 2>/dev/null || true
          fi
          
          # Добавляем новые файлы
          git add db.json
          git add checked/

      - name: Commit results
        run: |
          if ! git diff --staged --quiet; then
            git commit -m "Update proxy test results ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            
            # Force push чтобы не сохранять историю
            git push --force-with-lease https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
          else
            echo "No changes to test results."
          fi

      - name: Clean up Git history
        run: |
          # Опционально: очистка истории для экономии места
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive
